### ISSUE TITLE
Performance: requiring shim when Object.fromEntries exists should be a no-op

### ISSUE THREAD

**Issue by victor-homyakov** [es-shims/Object.fromEntries#2]
In case when `Object.fromEntries` already exists, `require('object.fromentries')` still requires and executes a lot of code (about 20-30 milliseconds on MacBook Pro with 2,7 GHz Intel Core i5).

It requires all the dependencies, builds its own polyfill, and only then realizes that there is nothing to polyfill. In fact, it should first check if there is any need of polyfill at all and exit early without requiring any optional dependencies. It is important when this shim is used in CLI tools like ESLint, where startup time is significant for user experience.

Also, when `Object.fromEntries` exists, this shim adds properties `getPolyfill` `implementation` `shim` to existing function. I think this can be avoided.

**Comment by ljharb** [comment]
Static unconditional requires are necessary for bundling; 20-30ms is not very significant in node.

As to your last point, that's definitely a bug, and I'll fix that asap.

**Comment by victor-homyakov** [comment]
> Static unconditional requires are necessary for bundling

OK, require the module statically, but do not evaluate anything inside of it eagerly - build polyfill only when it is required.

> 20-30ms is not very significant in node

Nowadays projects include hundreds or even thousands of modules. Even when only some of them require tens of milliseconds to initialize, the whole time to start the tool may be quite long.

**Comment by ljharb** [comment]
> build polyfill only when it is required

The file containing the implementation needs to be evaluated and bundled 100% of the time, so that a runtime check can be performed. The only possible optimization here would be a lazy require, which bundlers would have trouble with.

**Comment by victor-homyakov** [comment]
Is there a possibility to make a separate version for Node.js, with conditional requires?

**Comment by ljharb** [comment]
Yes, but that would be a large complexity and maintenance cost all for < 50 ms (comparing `time node -e 'require("./")'` to `time node -e ';'` in the project dir gives me anywhere from 15ms up to 50ms).

**Comment by ljharb** [comment]
Either way, a version "for node" would have to work simultaneously with old node versions that lack Object.fromEntries as well as newer ones that have it.

I don't think there's anything that can be done here; you can directly import `object.fromentries/polyfill` and run it, to get the best possible method, but that's about it.
