### ISSUE TITLE
TypeError: unable to create data property

### ISSUE THREAD

**Issue by dnalborczyk** [es-shims/Object.fromEntries#6]
repro, version: **v2.0.2** with node.js v10.19.0
```js
require('Object.fromEntries/auto.js')
Object.fromEntries([['foo', 1], ['foo', 2]])
```

```shell
Thrown:
TypeError: unable to create data property
    at CreateDataPropertyOrThrow (/node_modules/es-abstract/2019/CreateDataPropertyOrThrow.js:22:9)
    at Object.addDataProperty (/node_modules/Object.fromEntries/implementation.js:14:2)
    at Call (/node_modules/es-abstract/2019/Call.js:18:11)
    at AddEntriesFromIterable (/node_modules/es-abstract/2019/AddEntriesFromIterable.js:44:4)
    at Function.fromEntries (/node_modules/Object.fromEntries/implementation.js:47:9)
```

works with **v2.0.1** (as well as natively in node.js v12+, latest Chrome, latest Firefox)
```js
require('Object.fromEntries/auto.js')
Object.fromEntries([['foo', 1], ['foo', 2]])
// { foo: 2 }
```

**Comment by ljharb** [comment]
(as an aside; package names are lowercase - it should have to be `'object.fromentries/auto'`, not `Object.fromEntries`)

Thanks, I see the same error. I see it also in node 10.18, which passed here: https://travis-ci.com/github/es-shims/Object.fromEntries/jobs/282064492, so i'm not sure what would have changed.

**Comment by ljharb** [comment]
Seems like I'm just missing a test for duplicate keys; i'll take care of it. Thanks!

**Comment by ljharb** [comment]
Looks like it was a bug in es-abstract itself; a patch will be out shortly. I'll close this issue once it is with a dep bump + a test, but no release should be needed of this package due to semver ranges.

**Comment by dnalborczyk** [comment]
thank you for the quick fix @ljharb !

> (as an aside; package names are lowercase - it should have to be 'object.fromentries/auto', not Object.fromEntries)

yeah, that was just an oversight of a copy/paste error.
