### ISSUE TITLE
How to use from Typescript?

### ISSUE THREAD

**Issue by ariofrio** [es-shims/Object.fromEntries#8]
On Node 10.x, [Object.fromEntries is not supported](https://node.green/#ES2019-features--Object-fromEntries), so a shim is needed to use it. This is the official shim, but there seems to be no way to use it from TypeScript without manually including a typing in my project.

```
import fromEntries from "object.fromentries";
```

gives the following error:

```
TS7016: Could not find a declaration file for module 'object.fromentries'. '/Users/ariofrio/Work/RonaldCundy/rectecgrills-firebase/functions/node_modules/object.fromentries/index.js' implicitly has an 'any' type.   Try `npm install @types/object.fromentries` if it exists or add a new declaration (.d.ts) file containing `declare module 'object.fromentries';
```

However, there is no `@types/object.fromentries` package either.

Would you be open to adding the typings here, or would you rather they be added in DefinitelyTyped, or is there an alternative solution I haven't thought of? For instance, a version of the typings are already included in the TypeScript installation. Normally, they would be included using the following in tsconfig.json:

```
{
  "compilerOptions": {
    "lib": ["es2019"],
  }
}
```

Except that adds the function to Object, instead of as an importable function. And it includes all library features in ES2019 (I currently specify ES2018 which is largely supported by Node 10), not just this particular one, giving false positives if I try to use another.

This is probably an issue that is not unique to Object.fromEntries and applies to other shims in this organization.

For reference, here is the `object.fromentries.d.ts` I'm using in my project:

```
declare module "object.fromentries" {
  // Adapted from node_modules/typescript/lib/lib.es2019.object.d.ts

  /**
   * Returns an object created by key-value entries for properties and methods
   * @param entries An iterable object that contains key-value entries for properties and methods.
   */
  export default function fromEntries<T = any>(
    entries: Iterable<readonly [PropertyKey, T]>
  ): {
    [k in PropertyKey]: T;
  };

  /**
   * Returns an object created by key-value entries for properties and methods
   * @param entries An iterable object that contains key-value entries for properties and methods.
   */
  export default function fromEntries(entries: Iterable<readonly any[]>): any;
}
```

**Comment by ljharb** [comment]
It'd be fine to submit a PR to DefinitelyTyped to add the types package for `object.entries`; there's a few other es-shims in there.

I'm not interested in shipping types anywhere without a tool to keep them in sync with the JS, that doesn't require adding any annotations inside the JS.

(i'd use T and not any in the Iterable overload, fwiw)

**Comment by ariofrio** [comment]
I just [copied what the standard library says](https://github.com/microsoft/TypeScript/blob/master/lib/lib.es2019.object.d.ts). Which is "the Iterable overload"? Both overloads use Iterable, and both use any. Would appreciate it if you clarified your suggestion.

Also, what would such a tool look like? I've seen many package maintainer express similar sentiments (about shipping types without a tool to keep them in sync with JS without annotations), and I'm genuinely curious about what could help make our collective experience better.

**Comment by ljharb** [comment]
I'd suggest:
```ts
export default function fromEntries<T = unknown>(
    entries: Iterable<readonly [PropertyKey, T]>
  ): {
    [k in PropertyKey]: T;
  };

export default function fromEntries(entries: Iterable<readonly T[]>): {
  [k in PropertyKey]: T;
};
```
so that there's no "any" usage at all (even if the TS types aren't that rigorous).

I'm not sure, but I believe the TS team is exploring it.
